# Generated by Django 2.2.6 on 2020-01-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='project',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='project',
            name='can_read',
        ),
        migrations.RemoveField(
            model_name='task',
            name='inCharge',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
