# Generated by Django 2.2.6 on 2020-02-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='individual',
        ),
    ]
