# Generated by Django 2.2.6 on 2020-01-23 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200122_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='startDate',
        ),
    ]
